### ISSUE TITLE
Gives an error when used with <Field render method

### ISSUE THREAD

**Issue by hemure** [kmees/formik-office-ui-fabric-react#1]
I've tested this package and for basic use it's working very well. Thank you!

In my case I need to provide a custom onBlur handler to the fields. For the original fabric-ui-react components, this works when using the field rendering method:
              <Field
                name="id"
                render={({ field }) => (
                  <TextField {...field} onBlur={this.onBlur}/>
                )}
              />
But when I replace the TextField with a FormikTextField, I get an error:

Exception has occurred: TypeError
TypeError: Cannot read property 'errors' of undefined
    at getErrorMessage (c:\Dev\formik_pg\formik-pg\node_modules\formik-office-ui-fabric-react\dist\formik-office-ui-fabric-react.es6.js:51:1)
    at mapFieldToTextField (c:\Dev\formik_pg\formik-pg\node_modules\formik-office-ui-fabric-react\dist\formik-office-ui-fabric-react.es6.js:423:1)
    at FormikTextField (c:\Dev\formik_pg\formik-pg\node_modules\formik-office-ui-fabric-react\dist\formik-office-ui-fabric-react.es6.js:448:1)
    at mountIndeterminateComponent (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:15167:1)
    at beginWork (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:15692:1)
    at performUnitOfWork (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:18750:1)
    at workLoop (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:18791:1)
    at HTMLUnknownElement.callCallback (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:147:1)
    at Object.invokeGuardedCallbackDev (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:196:1)
    at invokeGuardedCallback (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:250:1)
    at replayUnitOfWork (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:17998:1)
    at renderRoot (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:18909:1)
    at performWorkOnRoot (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:19812:1)
    at performWork (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:19722:1)
    at performSyncWork (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:19696:1)
    at interactiveUpdates$1 (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:19984:1)
    at interactiveUpdates (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:2267:1)
    at dispatchInteractiveEvent (c:\Dev\formik_pg\formik-pg\node_modules\react-dom\cjs\react-dom.development.js:5081:1)

Hope someone can help fix this issue.
Thanks

**Comment by kevicency** [comment]
Sorry for the delay, I was on holiday. The error indicates, that the `form` property of the `fieldProps` is undefined. Do you have a `<Form />` component as a parent of the `<Field />` somewhere in your component tree?

Also, currently `FormikTextField` doesn't support providing a custom `onBlur` handler.  You should get a type error that says so. I'll add that in a future release though.

<img width="531" alt="screenshot 2019-01-17 at 13 25 22" src="https://user-images.githubusercontent.com/649769/51318720-6330cf00-1a5b-11e9-8752-e262bc8a8ec2.png">

**Comment by hemure** [comment]
Hi Kevin

Thanks for getting back to me.
By looking at your code I found out that there's no way to set onBlur. So I
had to fall back to a simpler implementation that did not involve your
library.
This is all bygones now, but I do believe that
formik-office-ui-fabric-react is a much needed library and that you will
get a lot of downloads - especially if you elaborate a bit on it.

Best,
Henrik

**Comment by kevicency** [comment]
thanks! :) i personally don't like using `onBlur` etc. and try to use changes in my form state/props for that functionality. But as I said, i might add support for them in a future release.
